CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# Display Configuration
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_INVERT=n
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n

# OLED Stroke Weight Optimization
CONFIG_LV_DRAW_SW_I1_LUM_THRESHOLD=96

# Built-in Widgets
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# Power Management
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=50000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# USB
CONFIG_ZMK_USB=y
# Đặt tên hiển thị cho bàn phím (tránh lỗi hiện chữ N/A khiến OS tưởng rác và ẩn đi)
CONFIG_ZMK_KEYBOARD_NAME="Aug1st"

# Tắt chế độ 2Mbps PHY và kéo công suất để máy tính/điện thoại dễ quét thấy hơn
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
